on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false -DprocessDependencies=false -DprocessPlugins=false
      - run: mvn clean package
      - run: mvn -B versions:set -DnextSnapshot=true -DgenerateBackupPoms=false -DprocessDependencies=false -DprocessPlugins=false
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'pom.xml'
          message: Bump pom version
          new_branch: main
          push: true
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      - run: gh release upload ${{ github.ref_name }} target/flat-jconsole-$VERSION.jar
        env:
          GITHUB_TOKEN: ${{ github.token }}
