on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: mvn -B versions:set -DnewVersion=${{ github.ref }} -DgenerateBackupPoms=false
      - run: mvn clean package
      - run: gh release upload ${{ github.ref }} flat-jconsole-${{ github.ref }}.jar
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
